version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll_container
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --host 0.0.0.0